String AUTH_BOX = 'AUTH_BOX';
String KEY_ORIGIN = 'KEY_ORIGIN';
String KEY_USERNAME = 'KEY_USERNAME';
String KEY_EMAIL = 'KEY_EMAIL';
String KEY_PASSWORD = 'KEY_PASSWORD';
String KEY_USER_ID = 'KEY_USER_ID';
String KEY_WIZARD_REQUEST = 'KEY_WIZARD_REQUEST';
String FIRST_TIME_OPEN_APP = 'KEY_FIRST_TIME_OPEN_APP';
String KEY_SELECTED_MEAL_PLAN_OPTION = 'KEY_SELECTED_MEAL_PLAN_OPTION';


int MAX_WIZARD_NON_USER_REQUEST = 2;