String AUTH_BOX = 'AUTH_BOX';
String KEY_ORIGIN = 'KEY_ORIGIN';
String KEY_USERNAME = 'KEY_USERNAME';
String KEY_EMAIL = 'KEY_EMAIL';
String KEY_PASSWORD = 'KEY_PASSWORD';
String KEY_USER_ID = 'KEY_USER_ID';