

const FREE_FAVORITE_LIMIT= 10;
const FREE_FOODS_PORTION_REQUEST_LIMIT= 0;
const FREE_SUGGEST_FOOD_LIMIT= 0;
const FREE_PLAN= 'free';



const BASIC_FOODS_PORTION_REQUEST_LIMIT= 50;
const BASIC_SUGGEST_FOOD_LIMIT= 100;
const BASIC_PLAN= 'basic';
const BASIC_PRICE_MONTHLY= 9.99;
const BASIC_PRICE_ANNUAL_MONTHLY= 7.99;


const PREMIUM_FOODS_PORTION_REQUEST_LIMIT= 150;
const PREMIUM_SUGGEST_FOOD_LIMIT= 300;
const PREMIUM_PLAN= 'premium';
const PREMIUM_PRICE_MONTHLY= 14.99;
const PREMIUM_PRICE_ANNUAL_MONTHLY= 11.99;


const DIETITIAN_PLAN= 'dietitian';


const MONTHLY_PLAN= 'monthly';
const ANNUAL_PLAN= 'annual';


const UNLIMITED= 'unlimited';

