name: masterpie
description: "a diet application"

version: 3.2.4+60



publish_to: 'none'

environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.0.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  freezed: ^2.1.0+1
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  json_annotation: ^4.8.0
  shared_preferences: ^2.0.15
  sqflite: ^2.3.3+1
  hive_flutter: ^1.1.0
  getwidget: ^3.1.1
  openfoodfacts: ^2.5.0
  percent_indicator: ^4.2.3
  intl: ^0.18.1
  http: ^1.1.0
  dart_openai: ^5.0.0
  envied: ^0.3.0
  google_sign_in: ^6.1.6
  supabase_flutter: ^1.10.3
  path_provider: ^2.0.2
  url_launcher: ^6.0.9
  package_info_plus: ^5.0.1
  flutter_config: ^2.0.2
  firebase_core: ^2.25.3
  firebase_crashlytics: ^3.4.13
  firebase_analytics: ^10.8.9
  oauth2: ^2.0.2
  flutter_barcode_scanner: ^2.0.0
  in_app_purchase: ^3.2.0
  in_app_purchase_storekit: ^0.3.4
  in_app_purchase_android: ^0.3.0
  flutter_expandable_fab: ^2.0.0
  showcaseview: ^3.0.0
  fraction: ^5.0.2
  device_info_plus: ^9.0.2
  flutter_secure_storage: ^9.2.2
  uuid: ^4.4.2


dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  flutter_launcher_icons: ^0.13.0


flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Bold.ttf


flutter_icons:
  android: true
  ios: true
  image_path: "assets/masterpie_logo_launcher.png"