const double BORDER_RADIUS = 10;
const double TOP_PADDING_SEARCH_CAT = 20;
const double LEFT_PADDING_SEARCH_CAT = 24;
const double RIGHT_MARGIN_SEARCH_CAT_LABEL = 24;
const double TOP_MARGIN_SEARCH_CAT = 12;
const double BOTTOM_MARGIN_SEARCH_CAT_LABEL = 12;
const double TITLE_FONT_SIZE = 13;
const double BTN_HEIGHT = 46;
const double FONT_WEIGH_INFO = 10;
const double FONT_CATS_LABEL = 12;
const double FONT_CALORIE_INFO = 8;
const double FONT_HEADER= 13;
const SIZE_IMAGE_CAT = 70.0;
const SIZE_IMAGE_UPGRADE_PLAN = 80.0;
const TABS_SIZE = 2;
const PADDING_SEARCH_HORIZONTAL = 30.0;
const PADDING_SEARCH_VERTICAL = 15.0;
const PADDING_MAIN_PAGE = 16.0;
const FAB_SIZE = 48.0;
const FONT_SIZE_TITLE = 15.0;
const FONT_SIZE_SUBTITLE = 13.0;
const MACRO_HEIGHT = 35.0;
const MACRO_WIDTH = 80.0;
const MACRO_TITLE_WIDTH = 60.0;
const UNIT_TITLE_WIDTH = 40.0;
const SEARCH_BAR_HEIGHT = 40.0;
const RECIPE_HEIGHT = 200.0;
const STEP_AMOUNT = 0.5;
const SERVING_MIN_DEFAULT = 0.5;
const SERVING_MAX_DEFAULT = 5.0;
const SERVING_MIN = 0.0;
const SERVING_MAX = 10.0;
const SERVING_DEVISION = 20;
const MACRO_DROP_DOWN_WIDTH = 100.0;
const MACRO_DROP_DOWN_HEIGHT = 35.0;


const TOP_PART_MAIN_SCREEN_HEIGHT = 370.0;
const DATE_CONTAINER_HEIGHT = 20.0;
const MACRO_CONTAINER_HEIGHT = 175.0;
const MACRO_MARGIN  = 6.0;
const MACRO_CIRCLE_RADIUS = 20.0;
const MACRO_ANIMATION_DURATION = 1200;
const MACRO_CIRCLE_WIDTH = 2.0;
const MACRO_LABEL_TOP_MARGIN = 16.0;
const MACRO_LABEL_FONT_SIZE = 11.0;


const CAT_LABEL_TOP_MARGIN = 8.0;

const CAT_HEIGHT = 210.0;



const MACRO_SIZE_WIDTH = 100.0;




