// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUHoirerRxM00_q5hVrDODj-ur3WrM4UE',
    appId: '1:1081274275068:android:d30440aadd9e015d8df379',
    messagingSenderId: '1081274275068',
    projectId: 'masterpie-389519',
    storageBucket: 'masterpie-389519.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgkVxzPm4aAGYBywznzLGu-zo-brmH-eU',
    appId: '1:1081274275068:ios:684ae9069963f8838df379',
    messagingSenderId: '1081274275068',
    projectId: 'masterpie-389519',
    storageBucket: 'masterpie-389519.appspot.com',
    androidClientId: '1081274275068-8hp1kq00lmoqtalhkmn3n71nuhji0ipn.apps.googleusercontent.com',
    iosClientId: '1081274275068-bcjg7ppmg2rpud2q71926t7o32amjghj.apps.googleusercontent.com',
    iosBundleId: 'com.mobile.masterpieapp',
  );
}
